export interface CodeStats {
  id?: number;           // Optional because it's generated by DB
  userId: number;        // Link to the users table
  day: number;           // Advent of Code day (1-25)
  part: 1 | 2;           // Part 1 or Part 2
  language: string;      // e.g., 'python', 'javascript'
  executionTimeMs: number;
  memoryUsageKb: number;
  codeLengthBytes: number;
  submittedAt: Date;
}

export interface LeaderboardFilter {
  day?: number;
  language?: string;
}
